---
- name: CloudWatch Agent 設定ファイルを配置する
  ansible.builtin.template:
    src: amazon-cloudwatch-agent.json.j2
    dest: "{{ cloudwatch_agent_config_path }}"
    mode: "0644"
  notify: CloudWatch Agent を再起動
