---
- name: CloudWatch Agent インストールタスクを読み込む
  ansible.builtin.import_tasks: install.yml

- name: CloudWatch Agent 設定タスクを読み込む
  ansible.builtin.import_tasks: configure.yml

- name: CloudWatch Agent サービスタスクを読み込む
  ansible.builtin.import_tasks: service.yml
